### ISSUE TITLE
Syntax error while importing utils

### ISSUE THREAD

**Issue by rusiaaman** [Zahlii/colab-tf-utils#1]
I get the following error:

```
  File "utils.py", line 62
    def upload_file_to_folder(self, local_file, folder: GDriveItem = None):
                                                      ^
SyntaxError: invalid syntax
```

**Comment by Zahlii** [comment]
Which Python version are you using? It sounds like a python 2 issue. I only tested the script with python3.6...

**Comment by rusiaaman** [comment]
Yes, I am using python 2. Do you think it can be made python 2 compatible without much effort?

**Comment by Zahlii** [comment]
If you have the time, you can try to fix it and make a pull request. In theory, this error should be removed by simply removing the type requirement; just put folder = None.

**Comment by Zahlii** [comment]
PR #2 merged, so I hope this issue is closed.
